const POSTS = [
  { title: 'The weather today', vote: 10, id: '1' },
  { title: 'The weather today', vote: 10, id: '2' },
  { title: 'The weather today', vote: 10, id: '3' },
  { title: 'The weather today', vote: 10, id: '4' },
  { title: 'The weather today', vote: 10, id: '5' },
  { title: 'The weather today', vote: 10, id: '6' },
  { title: 'The weather today', vote: 10, id: '1' },
  { title: 'The weather today', vote: 10, id: '2' },
  { title: 'The weather today', vote: 10, id: '3' },
  { title: 'The weather today', vote: 10, id: '4' },
  { title: 'The weather today', vote: 10, id: '5' },
  { title: 'The weather today', vote: 10, id: '6' },
  { title: 'The weather today', vote: 10, id: '1' },
  { title: 'The weather today', vote: 10, id: '2' },
  { title: 'The weather today', vote: 10, id: '3' },
  { title: 'The weather today', vote: 10, id: '4' },
  { title: 'The weather today', vote: 10, id: '5' },
  { title: 'The weather today', vote: 10, id: '6' },
  { title: 'The weather today', vote: 10, id: '1' },
  { title: 'The weather today', vote: 10, id: '2' },
  { title: 'The weather today', vote: 10, id: '3' },
  { title: 'The weather today', vote: 10, id: '4' },
  { title: 'The weather today', vote: 10, id: '5' },
  { title: 'The weather today', vote: 10, id: '6' },
];

export { POSTS };
